name: record_data
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  geolocator: ^12.0.0
  sensors_plus: ^5.0.1
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  device_info_plus: ^10.1.0
  uuid: ^4.4.2
  http: ^0.13.6
  flutter_map: ^4.0.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
